# Generated by Django 3.0.4 on 2020-03-13 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseSistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoia',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoia',
            name='meta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoia',
            name='src',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
