# Generated by Django 3.0.4 on 2020-03-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseSistema', '0003_auto_20200313_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoia',
            name='creationDate',
        ),
    ]
