# Generated by Django 3.0.4 on 2020-03-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSistema', '0004_remove_tipoia_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoia',
            name='src',
            field=models.URLField(default='https://source.unsplash.com/UUjxTEET0c0/1200x560', max_length=300),
        ),
    ]
