# Generated by Django 3.0.4 on 2020-04-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('baseSistema', '0004_auto_20200405_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDjango',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreApp', models.CharField(max_length=60)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
