# Generated by Django 3.0.4 on 2020-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSistema', '0005_tipoia_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoia',
            name='componentApp',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
