# Generated by Django 3.0.4 on 2020-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSistema', '0006_tipoia_componentapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoia',
            name='componentApp',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
