# Generated by Django 3.0.4 on 2020-03-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ColorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backgroundColor', models.CharField(max_length=50, verbose_name='identificador color de fondo')),
                ('textColor', models.CharField(max_length=50, verbose_name='identificador color de texto')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colorBack.RedColor')),
            ],
        ),
    ]
